CREATE TABLE bears (id INTEGER PRIMARY KEY, name TEXT);
ALTER TABLE bears ADD COLUMN age INTEGER;
ALTER TABLE bears ADD COLUMN gender TEXT;
ALTER TABLE bears ADD COLUMN color TEXT;
ALTER TABLE bears ADD COLUMN temperament TEXT;
ALTER TABLE bears ADD COLUMN alive BOOLEAN;

